// Simple script to create PNG icons - run with: node create-icons.js
const fs = require('fs');

// Minimal 192x192 red PNG (valid PNG format)
const png192Base64 = 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABd+13vAAAA/klEQVR4nO3QMQEAAADCoPVPbYhfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOA1v9EAATX68/0AAAAASUVORK5CYII=';

// Minimal 512x512 red PNG (valid PNG format)
const png512Base64 = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAABccqhmAAAAK0lEQVR4nO3BMQEAAADCoPVPbQ0PoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwDVA4AAbmzwIAAGrFXC0AAAAAElFTkSuQmCC';

try {
  fs.writeFileSync('dartboard-192.png', Buffer.from(png192Base64, 'base64'));
  fs.writeFileSync('dartboard-512.png', Buffer.from(png512Base64, 'base64'));
  console.log('Icons created successfully');
} catch (e) {
  console.error('Error creating icons:', e.message);
}
